# Generated by Django 4.0.5 on 2022-06-27 16:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название животного')),
                ('image', models.ImageField(blank=True, upload_to='photos_animal/Y/M/', verbose_name='Изображение животного')),
            ],
            options={
                'verbose_name': 'Тип животного',
                'verbose_name_plural': 'Типы Животных',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бренда')),
                ('image', models.ImageField(blank=True, upload_to='photos_brand/Y/M/', verbose_name='Изображение бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'БРЕНДЫ',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=100, verbose_name='Автор отзыва')),
                ('body_of_comment', models.TextField(verbose_name='Содержание отзыва')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('date_added', models.DateField(auto_now=True, verbose_name='Дата добавления отзыва')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Отзыв о магазине',
                'verbose_name_plural': 'ОТЗЫВЫ О МАГАЗИНЕ',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес магазина')),
                ('metro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Станция метро')),
                ('time_weekdays', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время работы (будни)')),
                ('time_weekend', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время работы (выходные)')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('social', models.TextField(blank=True, help_text='Вставить ссылку страницы социальной сети', null=True, verbose_name='Социальная сеть')),
                ('maps', models.TextField(blank=True, help_text='Вставить скрипт-ссылку с яндекс карты (размер 670х374)', verbose_name='Расположение на карте')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Информацию о магазине',
                'verbose_name_plural': 'ИНФОРМАЦИЯ О МАГАЗИНЕ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название товара')),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, upload_to='photos_products/Y/M/', verbose_name='Изображение товара'), size=None)),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('features', models.TextField(verbose_name='Ключевые особенности')),
                ('composition', models.TextField(verbose_name='Состав')),
                ('additives', models.TextField(verbose_name='Пищевые добавки')),
                ('analysis', models.TextField(verbose_name='Гарантированный анализ')),
                ('unit', models.CharField(choices=[('кг.', 'кг.'), ('гр.', 'гр.'), ('л.', 'л.'), ('мл.', 'мл.'), ('шт.', 'шт.')], max_length=10, verbose_name='Единица измерения')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.animal')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('size', models.PositiveIntegerField(verbose_name='Объём/Масса/Штук')),
                ('count', models.PositiveIntegerField(verbose_name='Остаток на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Продукт')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.producttype'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('description', models.TextField(verbose_name='Описание статьи')),
                ('image', models.ImageField(blank=True, upload_to='photos_article/Y/M/', verbose_name='Изображение статьи')),
                ('time_read', models.CharField(max_length=50, verbose_name='Время чтения статьи')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Дата добавления статьи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('animals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.animal', verbose_name='Название животного')),
            ],
            options={
                'verbose_name': 'Полезная статья',
                'verbose_name_plural': 'ПОЛЕЗНЫЕ СТАТЬИ',
                'ordering': ['-date_added'],
            },
        ),
    ]
